name: Version Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Trims latest release notes from CHANGELOG,md
      - name: Generate Release Notes
        run: sed '1p;1,/^##/!d;/##/d' CHANGELOG.md > ${{ github.ref_name }}.md

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.ref_name }}.md
        env:
          GITHUB_REPOSITORY: Argyle-Software/kyber